name: "recallwatch_dbt"
version: "1.0.0"
config-version: 2

profile: "recallwatch_dbt"

model-paths: ["models"]
test-paths: ["tests"]

models:
  recallwatch_dbt:
    staging:
      +schema: stg
      +materialized: view
    marts:
      +schema: mart
      +materialized: table